condense_wildcard_suffixes = true
format_code_in_doc_comments = true
max_width = 120
hard_tabs = true
imports_granularity="Crate"
overflow_delimited_expr = true
reorder_impl_items = true
use_field_init_shorthand = true
wrap_comments = true