[package]
name = "edgeware-runtime"
version = "3.1.0"
authors = ["Commonwealth Labs <hello@commonwealth.im>"]
edition = "2018"
build = "build.rs"

[package.metadata.wasm-pack.profile.release]
# `wasm-opt` has some problems on linux, see
# https://github.com/rustwasm/wasm-pack/issues/781 etc.
wasm-opt = false

[dependencies]
# third-party dependencies
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }
integer-sqrt = { version = "0.1.2" }
safe-mix = { version = "1.0", default-features = false }
rustc-hex = { version = "2.0", optional = true }
serde = { version = "1.0.102", optional = true }
static_assertions = "1.1.0"

# primitives
sp-application-crypto = { path = "../../vendor/frontier/vendor/substrate/primitives/application-crypto", default-features = false }
sp-authority-discovery = { path = "../../vendor/frontier/vendor/substrate/primitives/authority-discovery", default-features = false }
sp-consensus-aura = { path = "../../vendor/frontier/vendor/substrate/primitives/consensus/aura", default-features = false }
sp-block-builder = { path = "../../vendor/frontier/vendor/substrate/primitives/block-builder", default-features = false}
sp-inherents = { path = "../../vendor/frontier/vendor/substrate/primitives/inherents", default-features = false }
sp-core = { path = "../../vendor/frontier/vendor/substrate/primitives/core", default-features = false }
sp-std = { path = "../../vendor/frontier/vendor/substrate/primitives/std", default-features = false }
sp-api = { path = "../../vendor/frontier/vendor/substrate/primitives/api", default-features = false }
sp-runtime = { path = "../../vendor/frontier/vendor/substrate/primitives/runtime", default-features = false }
sp-staking = { path = "../../vendor/frontier/vendor/substrate/primitives/staking", default-features = false }
sp-keyring = { path = "../../vendor/frontier/vendor/substrate/primitives/keyring", optional = true }
sp-session = { path = "../../vendor/frontier/vendor/substrate/primitives/session", default-features = false }
sp-transaction-pool = { path = "../../vendor/frontier/vendor/substrate/primitives/transaction-pool", default-features = false }
sp-version = { path = "../../vendor/frontier/vendor/substrate/primitives/version", default-features = false }
sp-offchain = { path = "../../vendor/frontier/vendor/substrate/primitives/offchain", default-features = false }

# edgeware primitives
edgeware-primitives = { path = "../primitives", default-features = false }
frontier-rpc-primitives = { default-features = false, path = "../../vendor/frontier/rpc/primitives" }
ethereum = { default-features = false, package = "pallet-ethereum", path = "../../vendor/frontier/frame/ethereum" }

# pallet dependencies
pallet-authority-discovery = { path = "../../vendor/frontier/vendor/substrate/frame/authority-discovery", default-features = false }
pallet-authorship = { path = "../../vendor/frontier/vendor/substrate/frame/authorship", default-features = false }
pallet-aura = { path = "../../vendor/frontier/vendor/substrate/frame/aura", default-features = false }
pallet-balances = { path = "../../vendor/frontier/vendor/substrate/frame/balances", default-features = false }
pallet-collective = { path = "../../vendor/frontier/vendor/substrate/frame/collective", default-features = false }
pallet-contracts = { default-features = false, path = "../../vendor/frontier/vendor/substrate/frame/contracts" }
pallet-contracts-primitives = { default-features = false, path = "../../vendor/frontier/vendor/substrate/frame/contracts/common/" }
pallet-contracts-rpc-runtime-api = { default-features = false, path = "../../vendor/frontier/vendor/substrate/frame/contracts/rpc/runtime-api/" }
pallet-democracy = { path = "../../vendor/frontier/vendor/substrate/frame/democracy", default-features = false }
pallet-elections-phragmen = { path = "../../vendor/frontier/vendor/substrate/frame/elections-phragmen", default-features = false }
pallet-evm = { path = "../../vendor/frontier/vendor/substrate/frame/evm", default-features = false }
frame-executive = { path = "../../vendor/frontier/vendor/substrate/frame/executive", default-features = false }
pallet-finality-tracker = { path = "../../vendor/frontier/vendor/substrate/frame/finality-tracker", default-features = false }
pallet-grandpa = { path = "../../vendor/frontier/vendor/substrate/frame/grandpa", default-features = false }
pallet-identity = { path = "../../vendor/frontier/vendor/substrate/frame/identity", default-features = false }
pallet-im-online = { path = "../../vendor/frontier/vendor/substrate/frame/im-online", default-features = false }
pallet-indices = { path = "../../vendor/frontier/vendor/substrate/frame/indices", default-features = false }
pallet-multisig = { path = "../../vendor/frontier/vendor/substrate/frame/multisig", default-features = false }
pallet-offences = { path = "../../vendor/frontier/vendor/substrate/frame/offences", default-features = false }
pallet-proxy = { path = "../../vendor/frontier/vendor/substrate/frame/proxy", default-features = false }
pallet-randomness-collective-flip = { path = "../../vendor/frontier/vendor/substrate/frame/randomness-collective-flip", default-features = false }
pallet-recovery = { path = "../../vendor/frontier/vendor/substrate/frame/recovery", default-features = false }
pallet-scheduler = { path = "../../vendor/frontier/vendor/substrate/frame/scheduler", default-features = false }
pallet-session = { path = "../../vendor/frontier/vendor/substrate/frame/session", default-features = false, features = ["historical"] }
pallet-staking = { path = "../../vendor/frontier/vendor/substrate/frame/staking", default-features = false }
pallet-staking-reward-curve = { path = "../../vendor/frontier/vendor/substrate/frame/staking/reward-curve" }
pallet-sudo = { path = "../../vendor/frontier/vendor/substrate/frame/sudo", default-features = false }
frame-support = { path = "../../vendor/frontier/vendor/substrate/frame/support", default-features = false }
frame-system = { path = "../../vendor/frontier/vendor/substrate/frame/system", default-features = false }
frame-system-rpc-runtime-api = { path = "../../vendor/frontier/vendor/substrate/frame/system/rpc/runtime-api", default-features = false }
pallet-timestamp = { path = "../../vendor/frontier/vendor/substrate/frame/timestamp", default-features = false }
pallet-treasury = { path = "../../vendor/frontier/vendor/substrate/frame/treasury", default-features = false }
pallet-utility = { path = "../../vendor/frontier/vendor/substrate/frame/utility", default-features = false }
pallet-transaction-payment = { path = "../../vendor/frontier/vendor/substrate/frame/transaction-payment", default-features = false }
pallet-transaction-payment-rpc-runtime-api = { path = "../../vendor/frontier/vendor/substrate/frame/transaction-payment/rpc/runtime-api", default-features = false }
pallet-vesting = { path = "../../vendor/frontier/vendor/substrate/frame/vesting", default-features = false }


signaling = { package = "edge-signaling", path = "../../modules/edge-signaling", default-features = false }
treasury-reward = { package = "edge-treasury-reward", path = "../../modules/edge-treasury-reward", default-features = false }
voting = { package = "edge-voting", path = "../../modules/edge-voting", default-features = false }

[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", path = "../../vendor/frontier/vendor/substrate/utils/wasm-builder-runner", version = "1.0.4" }

[dev-dependencies]
sp-io = { path = "../../vendor/frontier/vendor/substrate/primitives/io" }

[features]
default = ["std"]
std = [
	"sp-authority-discovery/std",
	"pallet-authority-discovery/std",
	"pallet-authorship/std",
	"sp-consensus-aura/std",
	"pallet-aura/std",
	"pallet-balances/std",
	"sp-block-builder/std",
	"codec/std",
	"pallet-collective/std",
	"pallet-contracts/std",
	"pallet-contracts-primitives/std",
	"pallet-contracts-rpc-runtime-api/std",
	"pallet-democracy/std",
	"pallet-elections-phragmen/std",
	"pallet-evm/std",
	"frame-executive/std",
	"pallet-finality-tracker/std",
	"pallet-grandpa/std",
	"pallet-identity/std",
	"pallet-im-online/std",
	"pallet-indices/std",
	"pallet-multisig/std",
	"sp-inherents/std",
	"pallet-offences/std",
	"pallet-proxy/std",
	"pallet-recovery/std",
	"sp-core/std",
	"pallet-randomness-collective-flip/std",
	"sp-std/std",
	"rustc-hex",
	"safe-mix/std",
	"serde",
	"pallet-session/std",
	"sp-api/std",
	"sp-runtime/std",
	"sp-staking/std",
	"pallet-staking/std",
	"sp-keyring",
	"sp-session/std",
	"pallet-sudo/std",
	"pallet-scheduler/std",
	"frame-support/std",
	"frame-system-rpc-runtime-api/std",
	"frame-system/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-transaction-payment/std",
	"pallet-treasury/std",
	"sp-transaction-pool/std",
	"pallet-utility/std",
	"pallet-vesting/std",
	"sp-version/std",
	"sp-offchain/std",
	"edgeware-primitives/std",
	"signaling/std",
	"treasury-reward/std",
	"voting/std",
	"frontier-rpc-primitives/std",
	"ethereum/std",
]
