[package]
name = "edgeware-runtime"
version = "3.1.1"
authors = ["Commonwealth Labs <hello@commonwealth.im>"]
edition = "2018"
build = "build.rs"

[package.metadata.wasm-pack.profile.release]
# `wasm-opt` has some problems on linux, see
# https://github.com/rustwasm/wasm-pack/issues/781 etc.
wasm-opt = false

[dependencies]
# third-party dependencies
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }
integer-sqrt = { version = "0.1.2" }
safe-mix = { version = "1.0", default-features = false }
rustc-hex = { version = "2.0", optional = true }
serde = { version = "1.0.102", optional = true }
static_assertions = "1.1.0"

# primitives
sp-authority-discovery = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false }
sp-consensus-aura = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false }
sp-block-builder = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false}
sp-inherents = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false }
sp-api = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false }
sp-staking = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false }
sp-keyring = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", optional = true }
sp-session = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false }
sp-version = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false }
sp-offchain = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false }

# edgeware primitives
edgeware-primitives = { path = "../primitives", default-features = false }

# pallet dependencies
pallet-authority-discovery = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false }
pallet-authorship = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false }
pallet-aura = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false }
pallet-balances = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false }
pallet-collective = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false }
pallet-contracts = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false }
pallet-contracts-primitives = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false }
pallet-contracts-rpc-runtime-api = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false }
pallet-democracy = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false }
pallet-elections-phragmen = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false }
# pallet-evm = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false }
frame-executive = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false }
pallet-finality-tracker = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false }
pallet-grandpa = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false }
pallet-identity = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false }
pallet-im-online = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false }
pallet-indices = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false }
pallet-multisig = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false }
pallet-offences = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false }
pallet-proxy = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false }
pallet-randomness-collective-flip = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false }
pallet-recovery = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false }
pallet-scheduler = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false }
pallet-session = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false, features = ["historical"] }
pallet-staking = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false }
pallet-staking-reward-curve = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch" }
pallet-sudo = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false }
frame-support = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false }
pallet-timestamp = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false }
pallet-treasury = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false }
pallet-utility = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false }
pallet-vesting = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", default-features = false }


signaling = { package = "edge-signaling", path = "../../modules/edge-signaling", default-features = false }
treasury-reward = { package = "edge-treasury-reward", path = "../../modules/edge-treasury-reward", default-features = false }
voting = { package = "edge-voting", path = "../../modules/edge-voting", default-features = false }

[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch", version = "1.0.4" }

[dev-dependencies]
sp-io = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch" }

[features]
default = ["std"]
std = [
	"sp-authority-discovery/std",
	"pallet-authority-discovery/std",
	"pallet-authorship/std",
	"sp-consensus-aura/std",
	"pallet-aura/std",
	"pallet-balances/std",
	"sp-block-builder/std",
	"codec/std",
	"pallet-collective/std",
	"pallet-contracts-rpc-runtime-api/std",
	"pallet-contracts-primitives/std",
	"pallet-contracts/std",
	"pallet-democracy/std",
	"pallet-elections-phragmen/std",
	# "pallet-evm/std",
	"frame-executive/std",
	"pallet-finality-tracker/std",
	"pallet-grandpa/std",
	"pallet-identity/std",
	"pallet-im-online/std",
	"pallet-indices/std",
	"pallet-multisig/std",
	"sp-inherents/std",
	"pallet-offences/std",
	"pallet-proxy/std",
	"pallet-recovery/std",
	"sp-core/std",
	"pallet-randomness-collective-flip/std",
	"sp-std/std",
	"rustc-hex",
	"safe-mix/std",
	"serde",
	"pallet-session/std",
	"sp-api/std",
	"sp-runtime/std",
	"sp-staking/std",
	"pallet-staking/std",
	"sp-keyring",
	"sp-session/std",
	"pallet-sudo/std",
	"pallet-scheduler/std",
	"frame-support/std",
	"frame-system-rpc-runtime-api/std",
	"frame-system/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-transaction-payment/std",
	"pallet-treasury/std",
	"sp-transaction-pool/std",
	"pallet-utility/std",
	"pallet-vesting/std",
	"sp-version/std",
	"sp-offchain/std",
	"edgeware-primitives/std",
	"signaling/std",
	"treasury-reward/std",
	"voting/std",
]
