[package]
name = "edgeware-testing"
version = "3.0.0"
authors = ["Commonwealth Labs <hello@commonwealth.im>"]
description = "Test utilities for Edgeware."
edition = "2018"

[dependencies]
pallet-balances = { path = "../../vendor/frontier/vendor/substrate/frame/balances" }
codec = { package = "parity-scale-codec", version = "1.3.0" }
sc-service = { path = "../../vendor/frontier/vendor/substrate/client/service", features = ["test-helpers", "db"] }
pallet-grandpa = { path = "../../vendor/frontier/vendor/substrate/frame/grandpa" }
pallet-indices = { path = "../../vendor/frontier/vendor/substrate/frame/indices" }
sp-keyring = { path = "../../vendor/frontier/vendor/substrate/primitives/keyring" }
sp-core = { path = "../../vendor/frontier/vendor/substrate/primitives/core" }
sp-io = { path = "../../vendor/frontier/vendor/substrate/primitives/io" }
frame-support = { path = "../../vendor/frontier/vendor/substrate/frame/support" }
pallet-session = { path = "../../vendor/frontier/vendor/substrate/frame/session" }
sp-runtime = { path = "../../vendor/frontier/vendor/substrate/primitives/runtime" }
pallet-staking = { path = "../../vendor/frontier/vendor/substrate/frame/staking" }
sc-executor = { path = "../../vendor/frontier/vendor/substrate/client/executor" }
frame-system = { path = "../../vendor/frontier/vendor/substrate/frame/system" }
substrate-test-client = { path = "../../vendor/frontier/vendor/substrate/test-utils/client" }
pallet-timestamp = { path = "../../vendor/frontier/vendor/substrate/frame/timestamp" }
pallet-transaction-payment = { path = "../../vendor/frontier/vendor/substrate/frame/transaction-payment" }
pallet-treasury = { path = "../../vendor/frontier/vendor/substrate/frame/treasury" }
wabt = "0.10.0"

edgeware-executor = { path = "../executor" }
edgeware-primitives = { path = "../primitives" }
edgeware-runtime = { path = "../runtime" }
signaling = { package = "edge-signaling", path = "../../modules/edge-signaling" }
treasury-reward = { package = "edge-treasury-reward", path = "../../modules/edge-treasury-reward" }