[package]
name = "edgeware-rpc"
version = "2.0.0"
authors = ["Commonwealth Labs <hello@commonwealth.im>"]
edition = "2018"

[dependencies]
jsonrpc-core = "14.0.3"
sc-client = { git = "https://github.com/paritytech/substrate.git" }
sp-runtime = { git = "https://github.com/paritytech/substrate.git" }
pallet-contracts-rpc = { git = "https://github.com/paritytech/substrate.git" }
pallet-transaction-payment-rpc = { git = "https://github.com/paritytech/substrate.git" }
substrate-frame-rpc-system = { git = "https://github.com/paritytech/substrate.git" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate.git" }
edgeware-primitives = { path = "../primitives" }
edgeware-runtime = { path = "../runtime" }