[package]
name = "edgeware-rpc"
version = "3.2.0"
authors = ["Commonwealth Labs <hello@commonwealth.im>"]
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
jsonrpc-core = "15.0.0"
jsonrpc-pubsub = "15.0.0"
edgeware-primitives = { path = "../primitives" }
edgeware-runtime = { path = "../runtime" }
pallet-contracts-rpc = { version = "0.8.0" }
pallet-transaction-payment-rpc = { version = "2.0.0" }
sc-client-api = { version = "2.0.0" }
sc-consensus-aura = { version = "0.8.0" }
sc-consensus-epochs = { version = "0.8.0" }
sc-finality-grandpa = { version = "0.8.0" }
sc-finality-grandpa-rpc = { version = "0.8.0" }
sc-keystore = { version = "2.0.0" }
sc-network = { version = "0.8.0" }
sc-rpc-api = { version = "0.8.0" }
sc-rpc = { version = "2.0.0" }
sp-api = { version = "2.0.0" }
sp-block-builder = { version = "2.0.0" }
sp-blockchain = { version = "2.0.0" }
sp-consensus = { version = "0.8.1" }
sp-consensus-aura = { version = "0.8.0" }
sp-runtime = { version = "2.0.0" }
sp-transaction-pool = { version = "2.0.0" }
substrate-frame-rpc-system = { version = "2.0.0" }
pallet-ethereum = { version = "0.1.0" }
fc-rpc = { version = "0.1.0" }
fp-rpc = { version = "0.1.0" }
fc-rpc-core = { version = "0.1.0" }
