[package]
name = "edgeware-rpc"
version = "3.3.0"
authors = ["Commonwealth Labs <hello@commonwealth.im>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
description = "Edgeware rpc"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
jsonrpc-core = "15.0.0"
jsonrpc-pubsub = "15.0.0"
edgeware-primitives = { path = "../primitives" }
edgeware-runtime = { path = "../runtime" }
pallet-contracts-rpc = { version = "3.0" }
pallet-transaction-payment-rpc = { version = "3.0" }
sc-client-api = { version = "3.0" }
sc-consensus-aura = { version = "0.9" }
sc-consensus-epochs = { version = "0.9" }
sc-finality-grandpa = { version = "0.9" }
sc-finality-grandpa-rpc = { version = "0.9" }
sc-keystore = { version = "3.0" }
sc-network = { version = "0.9" }
sc-rpc-api = { version = "0.9" }
sc-rpc = { version = "3.0" }
sp-api = { version = "3.0" }
sp-block-builder = { version = "3.0" }
sp-blockchain = { version = "3.0" }
sp-consensus = { version = "0.9" }
sp-consensus-aura = { version = "0.9" }
sp-runtime = { version = "3.0" }
sp-transaction-pool = { version = "3.0" }
substrate-frame-rpc-system = { version = "3.0" }
pallet-ethereum = { git = "https://github.com/webb-tools/frontier", branch = "erup-4" }
fc-rpc = { default-features = false, git = "https://github.com/webb-tools/frontier", branch = "erup-4" }
fp-rpc = { default-features = false, git = "https://github.com/webb-tools/frontier", branch = "erup-4" }
fc-rpc-core = { default-features = false, git = "https://github.com/webb-tools/frontier", branch = "erup-4" }
fc-db = { default-features = false, git = "https://github.com/webb-tools/frontier", branch = "erup-4" }