version: 2
jobs:
  build:
    docker:
      - image: phusion/baseimage:0.11
        environment:
          DEBUG_BUILD: true
          DEBIAN_FRONTEND: noninteractive

    working_directory: ~/edgeware

    steps:
      - checkout
      - run: apt-get update
      - run: ~/edgeware/scripts/init.sh
      - run: cd ~/edgeware && git submodule update --init --recursive

      # module test cases
      - run: source ~/.cargo/env && cd ~/edgeware && ./scripts/test.sh

      # ts test cases
      - run: apt-get install yarn -y
      - run: cd ~/edgeware/ts-tests/frontier-tester && yarn
      - run: cd ~/edgeware/ts-tests/frontier-tester && yarn test-ci
