[package]
name = "edgeware-inspect"
version = "3.0.0"
authors = ["Commonwealth Labs <hello@commonwealth.im>"]
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.0" }
derive_more = "0.99"
log = "0.4.8"
sc-cli = { git = "https://github.com/hicommonwealth/substrate.git", branch = "apopiak-migrations" }
sc-client-api = { git = "https://github.com/hicommonwealth/substrate.git", branch = "apopiak-migrations" }
sc-service = { default-features = false, git = "https://github.com/hicommonwealth/substrate.git", branch = "apopiak-migrations" }
sp-blockchain = { git = "https://github.com/hicommonwealth/substrate.git", branch = "apopiak-migrations" }
sp-core = { git = "https://github.com/hicommonwealth/substrate.git", branch = "apopiak-migrations" }
sp-runtime = { git = "https://github.com/hicommonwealth/substrate.git", branch = "apopiak-migrations" }
structopt = "0.3.8"
