[package]
name = "edgeware-runtime-interface"
version = "3.0.0"
authors = ["Commonwealth Labs <hello@commonwealth.im>"]
description = "Edgeware runtime interface helpers and functions"
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.0" }
sp-runtime = { git = "https://github.com/hicommonwealth/substrate.git", branch = "apopiak-fix-session-migration" }
sp-runtime-interface = { git = "https://github.com/hicommonwealth/substrate.git", branch = "apopiak-fix-session-migration" }
sp-runtime-interface-proc-macro = { git = "https://github.com/hicommonwealth/substrate.git", branch = "apopiak-fix-session-migration" }
edgeware-primitives = { path = "../primitives" }

[features]
default = [ "std" ]
std = [
  "sp-runtime/std",
  "sp-runtime-interface/std",
]