version: '3.3'
services:
  edgeware:
    image: hicommonwealth/edgeware:v3.3.3
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "2"
    ports:
      - "127.0.0.1:9933:9933"
      - "127.0.0.1:9944:9944"
      - "127.0.0.1:30333:30333"
    command: ['--chain', '/data/node/cli/res/mainnet.chainspec.json', '--name', 'docker_compose_mainnet', '--ws-external', '--rpc-external', '--rpc-cors', 'all' ]
