[package]
name = "edgeware-rpc-txpool"
version = '0.6.0'
authors = ['PureStake']
edition = '2018'
homepage = 'https://edgewa.re'
license = 'GPL-3.0-only'
repository = 'https://github.com/PureStake/moonbeam/'

[dependencies]
sha3 = "0.8"
jsonrpc-core = "15.0.0"
ethereum-types = "0.11.0"
ethereum = { version = "0.7.1", default-features = false, features = ["with-codec"] }
edgeware-rpc-core-txpool = { path = "../../rpc-core/txpool" }
sp-runtime = { version = "3.0" }
sp-api = { version = "3.0" }
sp-io = { version = "3.0" }
sp-std = { version = "3.0" }
sp-blockchain = { version = "3.0" }
sp-transaction-pool = { version = "3.0" }
sc-transaction-graph = { version = "3.0" }
frame-system = { version = "3.0" }
serde = { version = "1.0", features = ["derive"] }

edgeware-rpc-primitives-txpool = { path = "../../../node/txpool" }
fc-rpc = { git = "https://github.com/webb-tools/frontier", branch = "erup-4-minimal-changes" }