[package]
name = "edge-treasury-reward"
version = "1.0.0"
authors = ["drewstone <drewstone329@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", default-features = false, optional = true }
serde_derive = { version = "1.0", optional = true }
safe-mix = { version = "1.0", default-features = false }
parity-codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
substrate-keyring = { git = "https://github.com/hicommonwealth/substrate.git", branch = "testnet-v0.9.0", optional = true }
substrate-primitives = { git = "https://github.com/hicommonwealth/substrate.git", branch = "testnet-v0.9.0", default-features = false }
sr-staking-primitives = { git = "https://github.com/hicommonwealth/substrate.git", branch = "testnet-v0.9.0", default-features = false }
sr-std = { git = "https://github.com/hicommonwealth/substrate.git", branch = "testnet-v0.9.0", default-features = false }
sr-io = { git = "https://github.com/hicommonwealth/substrate.git", branch = "testnet-v0.9.0", default-features = false }
sr-primitives = { git = "https://github.com/hicommonwealth/substrate.git", branch = "testnet-v0.9.0", default-features = false }
srml-support = { git = "https://github.com/hicommonwealth/substrate.git", branch = "testnet-v0.9.0", default-features = false }
srml-system = { git = "https://github.com/hicommonwealth/substrate.git", branch = "testnet-v0.9.0", default-features = false }
srml-staking = { git = "https://github.com/hicommonwealth/substrate.git", branch = "testnet-v0.9.0", default-features = false }
srml-session = { git = "https://github.com/hicommonwealth/substrate.git", branch = "testnet-v0.9.0", default-features = false }
srml-balances = { git = "https://github.com/hicommonwealth/substrate.git", branch = "testnet-v0.9.0", default-features = false }
srml-treasury = { git = "https://github.com/hicommonwealth/substrate.git", branch = "testnet-v0.9.0", default-features = false }
srml-timestamp = { git = "https://github.com/hicommonwealth/substrate.git", branch = "testnet-v0.9.0", default-features = false }

[features]
default = ["std"]
std = [
	"serde/std",
	"serde_derive",
	"safe-mix/std",
	"parity-codec/std",
	"substrate-primitives/std",
	"sr-std/std",
	"sr-io/std",
	"srml-support/std",
	"srml-system/std",
	"srml-staking/std",
	"srml-session/std",
	"sr-primitives/std",
	"srml-treasury/std",
	"srml-balances/std",
	"srml-timestamp/std",
	"sr-staking-primitives/std",
]
