[package]
name = "edgeware-cli"
version = "2.0.0"
authors = ["Commonwealth Labs <hello@commonwealth.im>"]
description = "Edgeware implementation using a substrate node."
build = "build.rs"
edition = "2018"
default-run = "edgeware"

[badges]
travis-ci = { repository = "paritytech/substrate", branch = "master" }
maintenance = { status = "actively-developed" }
is-it-maintained-issue-resolution = { repository = "paritytech/substrate" }
is-it-maintained-open-issues = { repository = "paritytech/substrate" }

[[bin]]
name = "edgeware"
path = "bin/main.rs"
required-features = ["cli"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# third-party dependencies
codec = { package = "parity-scale-codec", version = "1.0.6" }
serde = { version = "1.0.102", features = ["derive"] }
futures01 = { package = "futures", version = "0.1.29" }
futures = { version = "0.3.1", features = ["compat"] }
hex-literal = "0.2.1"
jsonrpc-core = "14.0.3"
log = "0.4.8"
rand = "0.7.2"
structopt = "=0.3.7"
hex = "0.3.2"
serde_json = "1.0"

# primitives
sp-authority-discovery = { git = "https://github.com/paritytech/substrate.git" }
sp-consensus-aura = { git = "https://github.com/paritytech/substrate.git"}
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate.git" }
sp-core = { git = "https://github.com/paritytech/substrate.git" }
sp-runtime = { git = "https://github.com/paritytech/substrate.git" }
sp-timestamp = { git = "https://github.com/paritytech/substrate.git", default-features = false }
sp-finality-tracker = { git = "https://github.com/paritytech/substrate.git", default-features = false }
sp-inherents = { git = "https://github.com/paritytech/substrate.git" }
sp-keyring = { git = "https://github.com/paritytech/substrate.git" }
sp-io = { git = "https://github.com/paritytech/substrate.git" }

# client dependencies
sc-client-api = { git = "https://github.com/paritytech/substrate.git" }
sc-client = { git = "https://github.com/paritytech/substrate.git" }
sc-chain-spec = { git = "https://github.com/paritytech/substrate.git" }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate.git" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate.git" }
sc-network = { git = "https://github.com/paritytech/substrate.git" }
sc-consensus-aura = { git = "https://github.com/paritytech/substrate.git" }
sc-finality-grandpa = { git = "https://github.com/paritytech/substrate.git" }
sc-client-db = { git = "https://github.com/paritytech/substrate.git" }
sc-offchain = { git = "https://github.com/paritytech/substrate.git" }
sc-rpc = { git = "https://github.com/paritytech/substrate.git" }
sc-basic-authority = { git = "https://github.com/paritytech/substrate.git" }
sc-service = { git = "https://github.com/paritytech/substrate.git", default-features = false }
sc-telemetry = { git = "https://github.com/paritytech/substrate.git" }
sc-authority-discovery = { git = "https://github.com/paritytech/substrate.git" }
sp-consensus = { git = "https://github.com/paritytech/substrate.git" }

# frame dependencies
pallet-indices = { git = "https://github.com/paritytech/substrate.git" }
pallet-timestamp = { git = "https://github.com/paritytech/substrate.git", default-features = false }
pallet-contracts = { git = "https://github.com/paritytech/substrate.git" }
frame-system = { git = "https://github.com/paritytech/substrate.git" }
pallet-balances = { git = "https://github.com/paritytech/substrate.git" }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate.git" }
frame-support = { git = "https://github.com/paritytech/substrate.git", default-features = false }
pallet-im-online = { git = "https://github.com/paritytech/substrate.git", default-features = false }
pallet-authority-discovery = { git = "https://github.com/paritytech/substrate.git" }

# node-specific dependencies
edgeware-runtime = { path = "../runtime" }
edgeware-rpc = { path = "../rpc" }
edgeware-primitives = { path = "../primitives" }
edgeware-executor = { path = "../executor" }

# CLI-specific dependencies
tokio = { version = "0.1.22", optional = true }
sc-cli = { git = "https://github.com/paritytech/substrate.git", optional = true }
node-transaction-factory = { git = "https://github.com/paritytech/substrate.git", optional = true }
ctrlc = { version = "3.1.3", features = ["termination"], optional = true }

# WASM-specific dependencies
wasm-bindgen = { version = "0.2.57", optional = true }
wasm-bindgen-futures = { version = "0.4.7", optional = true }
browser-utils = { git = "https://github.com/paritytech/substrate.git", optional = true }

[dev-dependencies]
sc-keystore = { git = "https://github.com/paritytech/substrate.git" }
sc-service-test = { git = "https://github.com/paritytech/substrate.git" }
futures = "0.3.1"
tempfile = "3.1.0"

[build-dependencies]
sc-cli = { git = "https://github.com/paritytech/substrate.git" }
build-script-utils = { package = "substrate-build-script-utils", git = "https://github.com/paritytech/substrate.git" }
structopt = "=0.3.7"
vergen = "3.0.4"

[features]
default = ["cli"]
browser = [
	"browser-utils",
	"wasm-bindgen",
	"wasm-bindgen-futures",
]
cli = [
	"sc-cli",
	"node-transaction-factory",
	"tokio",
	"ctrlc",
	"sc-service/rocksdb",
	"edgeware-executor/wasmi-errno",
]
wasmtime = [
	"cli",
	"edgeware-executor/wasmtime",
	"sc-cli/wasmtime",
	"sc-service/wasmtime",
]