[package]
name = "edgeware-cli"
version = "3.0.8"
authors = ["Commonwealth Labs <hello@commonwealth.im>"]
description = "Edgeware implementation using a substrate node."
build = "build.rs"
edition = "2018"
default-run = "edgeware"

[package.metadata.wasm-pack.profile.release]
# `wasm-opt` has some problems on linux, see
# https://github.com/rustwasm/wasm-pack/issues/781 etc.
wasm-opt = false

[badges]
travis-ci = { repository = "hicommonwealth/edgeware-node", branch = "master" }
maintenance = { status = "actively-developed" }
is-it-maintained-issue-resolution = { repository = "hicommonwealth/edgeware-node" }
is-it-maintained-open-issues = { repository = "hicommonwealth/edgeware-node" }

[[bin]]
name = "edgeware"
path = "bin/main.rs"
required-features = ["cli"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# third-party dependencies
codec = { package = "parity-scale-codec", version = "1.3.0" }
serde = { version = "1.0.102", features = ["derive"] }
futures = { version = "0.3.1", features = ["compat"] }
hex-literal = "0.2.1"
jsonrpc-core = "14.0.3"
log = "0.4.8"
rand = "0.7.2"
structopt = { version = "0.3.8", optional = true }
tracing = "0.1.10"
parking_lot = "0.10.0"
hex = "0.3.2"
serde_json = "1.0"

# primitives
sp-authority-discovery = { path = "../../vendor/frontier/vendor/substrate/primitives/authority-discovery" }
sp-consensus-aura = { path = "../../vendor/frontier/vendor/substrate/primitives/consensus/aura" }
sp-finality-grandpa = { path = "../../vendor/frontier/vendor/substrate/primitives/finality-grandpa" }
sp-core = { path = "../../vendor/frontier/vendor/substrate/primitives/core" }
sp-runtime = { path = "../../vendor/frontier/vendor/substrate/primitives/runtime" }
sp-timestamp = { path = "../../vendor/frontier/vendor/substrate/primitives/timestamp", default-features = false }
sp-finality-tracker = { path = "../../vendor/frontier/vendor/substrate/primitives/finality-tracker", default-features = false }
sp-inherents = { path = "../../vendor/frontier/vendor/substrate/primitives/inherents" }
sp-keyring = { path = "../../vendor/frontier/vendor/substrate/primitives/keyring" }
sp-io = { path = "../../vendor/frontier/vendor/substrate/primitives/io" }
sp-consensus = { path = "../../vendor/frontier/vendor/substrate/primitives/consensus/common" }
sp-transaction-pool = { path = "../../vendor/frontier/vendor/substrate/primitives/transaction-pool" }

# client dependencies
sc-client-api = { path = "../../vendor/frontier/vendor/substrate/client/api" }
sc-chain-spec = { path = "../../vendor/frontier/vendor/substrate/client/chain-spec" }
sc-consensus = { path = "../../vendor/frontier/vendor/substrate/client/consensus/common" }
sc-transaction-pool = { path = "../../vendor/frontier/vendor/substrate/client/transaction-pool" }
sc-network = { path = "../../vendor/frontier/vendor/substrate/client/network" }
sc-consensus-aura = { path = "../../vendor/frontier/vendor/substrate/client/consensus/aura" }
sc-finality-grandpa = { path = "../../vendor/frontier/vendor/substrate/client/finality-grandpa" }
sc-client-db = { path = "../../vendor/frontier/vendor/substrate/client/db", default-features = false }
sc-offchain = { path = "../../vendor/frontier/vendor/substrate/client/offchain" }
sc-rpc = { path = "../../vendor/frontier/vendor/substrate/client/rpc" }
sc-basic-authorship = { path = "../../vendor/frontier/vendor/substrate/client/basic-authorship" }
sc-service = { path = "../../vendor/frontier/vendor/substrate/client/service", default-features = false }
sc-tracing = { path = "../../vendor/frontier/vendor/substrate/client/tracing" }
sc-telemetry = { path = "../../vendor/frontier/vendor/substrate/client/telemetry" }
sc-authority-discovery = { path = "../../vendor/frontier/vendor/substrate/client/authority-discovery" }


# frame dependencies
pallet-indices = { path = "../../vendor/frontier/vendor/substrate/frame/indices" }
pallet-timestamp = { path = "../../vendor/frontier/vendor/substrate/frame/timestamp", default-features = false }
frame-system = { path = "../../vendor/frontier/vendor/substrate/frame/system" }
pallet-balances = { path = "../../vendor/frontier/vendor/substrate/frame/balances" }
pallet-transaction-payment = { path = "../../vendor/frontier/vendor/substrate/frame/transaction-payment" }
pallet-transaction-payment-rpc-runtime-api = { path = "../../vendor/frontier/vendor/substrate/frame/transaction-payment/rpc/runtime-api" }
frame-support = { path = "../../vendor/frontier/vendor/substrate/frame/support", default-features = false }
pallet-im-online = { path = "../../vendor/frontier/vendor/substrate/frame/im-online", default-features = false }
pallet-authority-discovery = { path = "../../vendor/frontier/vendor/substrate/frame/authority-discovery" }
frame-system-rpc-runtime-api = { path = "../../vendor/frontier/vendor/substrate/frame/system/rpc/runtime-api" }
pallet-evm = { path = "../../vendor/frontier/vendor/substrate/frame/evm" }

# node-specific dependencies
edgeware-runtime = { path = "../runtime" }
edgeware-rpc = { path = "../rpc" }
edgeware-primitives = { path = "../primitives" }
edgeware-executor = { path = "../executor" }

# CLI-specific dependencies
edgeware-inspect = { version = "3.0.0", optional = true, path = "../inspect" }
sc-cli = { path = "../../vendor/frontier/vendor/substrate/client/cli", optional = true }
frame-benchmarking-cli = { optional = true, path = "../../vendor/frontier/vendor/substrate/utils/frame/benchmarking-cli" }


# WASM-specific dependencies
wasm-bindgen = { version = "0.2.57", optional = true }
wasm-bindgen-futures = { version = "0.4.7", optional = true }
browser-utils = { package = "substrate-browser-utils", path = "../../vendor/frontier/vendor/substrate/utils/browser", optional = true }

[target.'cfg(target_arch="x86_64")'.dependencies]
node-executor = { path = "../../vendor/frontier/vendor/substrate/bin/node/executor", features = [ "wasmtime" ] }
sc-cli = { path = "../../vendor/frontier/vendor/substrate/client/cli", optional = true, features = [ "wasmtime" ] }
sc-service = { path = "../../vendor/frontier/vendor/substrate/client/service", default-features = false, features = [ "wasmtime" ] }

[dev-dependencies]
sc-keystore = { path = "../../vendor/frontier/vendor/substrate/client/keystore" }
sc-service-test = { path = "../../vendor/frontier/vendor/substrate/client/service/test" }
futures = "0.3.4"
tempfile = "3.1.0"
assert_cmd = "1.0"
nix = "0.17"
serde_json = "1.0"
regex = "1"
platforms = "0.2.1"

[build-dependencies]
sc-cli = { path = "../../vendor/frontier/vendor/substrate/client/cli", optional = true }
substrate-build-script-utils = { path = "../../vendor/frontier/vendor/substrate/utils/build-script-utils", optional = true }
structopt = { version = "0.3.8", optional = true }
edgeware-inspect = { version = "3.0.0", optional = true, path = "../inspect" }
frame-benchmarking-cli = { optional = true, path = "../../vendor/frontier/vendor/substrate/utils/frame/benchmarking-cli" }


[features]
default = ["cli", "wasmtime"]
browser = [
	"browser-utils",
	"wasm-bindgen",
	"wasm-bindgen-futures",
]
cli = [
	"edgeware-inspect",
	"edgeware-executor/wasmi-errno",
	"sc-cli",
	"frame-benchmarking-cli",
	"sc-service/db",
	"structopt",
	"substrate-build-script-utils",
]
wasmtime = [
	"cli",
	"edgeware-executor/wasmtime",
	"sc-cli/wasmtime",
	"sc-service/wasmtime",
]
