[package]
name = "edgeware-executor"
version = "3.0.0"
authors = ["Commonwealth Labs <hello@commonwealth.im>"]
description = "Edgeware implementation using a substrate node."
edition = "2018"

[dependencies]
trie-root = "0.16.0"
codec = { package = "parity-scale-codec", version = "1.3.0" }
sp-io = { path = "../../vendor/frontier/vendor/substrate/primitives/io" }
sp-state-machine = { path = "../../vendor/frontier/vendor/substrate/primitives/state-machine" }
sc-executor = { path = "../../vendor/frontier/vendor/substrate/client/executor" }
sp-core = { path = "../../vendor/frontier/vendor/substrate/primitives/core" }
sp-trie = { path = "../../vendor/frontier/vendor/substrate/primitives/trie" }
frame-benchmarking = { path = "../../vendor/frontier/vendor/substrate/frame/benchmarking" }

edgeware-primitives = { path = "../primitives" }
edgeware-runtime = { path = "../runtime" }
edgeware-runtime-interface = { path = "../runtime-interface" }

[dev-dependencies]
test-client = { package = "substrate-test-client", path = "../../vendor/frontier/vendor/substrate/test-utils/client" }
sp-runtime = { path = "../../vendor/frontier/vendor/substrate/primitives/runtime" }
frame-support = { path = "../../vendor/frontier/vendor/substrate/frame/support" }
pallet-balances = { path = "../../vendor/frontier/vendor/substrate/frame/balances" }
pallet-transaction-payment = { path = "../../vendor/frontier/vendor/substrate/frame/transaction-payment" }
pallet-session = { path = "../../vendor/frontier/vendor/substrate/frame/session" }
frame-system = { path = "../../vendor/frontier/vendor/substrate/frame/system" }
pallet-timestamp = { path = "../../vendor/frontier/vendor/substrate/frame/timestamp" }
pallet-treasury = { path = "../../vendor/frontier/vendor/substrate/frame/treasury" }
pallet-grandpa = { path = "../../vendor/frontier/vendor/substrate/frame/grandpa" }
pallet-indices = { path = "../../vendor/frontier/vendor/substrate/frame/indices" }
wabt = "0.10.0"
criterion = "0.3.0"

edgeware-testing = { path = "../testing" }

[features]
wasmtime = [
    "sc-executor/wasmtime",
]
wasmi-errno = [
    "sc-executor/wasmi-errno",
]
stress-test = []

[[bench]]
name = "bench"
harness = false
