[package]
name = "edgeware-executor"
version = "3.1.0"
authors = ["Commonwealth Labs <hello@commonwealth.im>"]
description = "Edgeware implementation using a substrate node."
edition = "2018"

[dependencies]
trie-root = "0.16.0"
codec = { package = "parity-scale-codec", version = "1.3.0" }
sp-io = { git = "https://github.com/hicommonwealth/substrate.git", branch = "drew-time-travel-up" }
sp-state-machine = { git = "https://github.com/hicommonwealth/substrate.git", branch = "drew-time-travel-up" }
sc-executor = { git = "https://github.com/hicommonwealth/substrate.git", branch = "drew-time-travel-up" }
sp-core = { git = "https://github.com/hicommonwealth/substrate.git", branch = "drew-time-travel-up" }
sp-trie = { git = "https://github.com/hicommonwealth/substrate.git", branch = "drew-time-travel-up" }
frame-benchmarking = { git = "https://github.com/hicommonwealth/substrate.git", branch = "drew-time-travel-up" }

edgeware-primitives = { path = "../primitives" }
edgeware-runtime = { path = "../runtime" }
edgeware-runtime-interface = { path = "../runtime-interface" }

[dev-dependencies]
test-client = { package = "substrate-test-client", git = "https://github.com/hicommonwealth/substrate.git", branch = "drew-time-travel-up" }
sp-runtime = { git = "https://github.com/hicommonwealth/substrate.git", branch = "drew-time-travel-up" }
frame-support = { git = "https://github.com/hicommonwealth/substrate.git", branch = "drew-time-travel-up" }
pallet-balances = { git = "https://github.com/hicommonwealth/substrate.git", branch = "drew-time-travel-up" }
pallet-transaction-payment = { git = "https://github.com/hicommonwealth/substrate.git", branch = "drew-time-travel-up" }
pallet-session = { git = "https://github.com/hicommonwealth/substrate.git", branch = "drew-time-travel-up" }
frame-system = { git = "https://github.com/hicommonwealth/substrate.git", branch = "drew-time-travel-up" }
pallet-timestamp = { git = "https://github.com/hicommonwealth/substrate.git", branch = "drew-time-travel-up" }
pallet-treasury = { git = "https://github.com/hicommonwealth/substrate.git", branch = "drew-time-travel-up" }
pallet-contracts = { git = "https://github.com/hicommonwealth/substrate.git", branch = "drew-time-travel-up" }
pallet-grandpa = { git = "https://github.com/hicommonwealth/substrate.git", branch = "drew-time-travel-up" }
pallet-indices = { git = "https://github.com/hicommonwealth/substrate.git", branch = "drew-time-travel-up" }
wabt = "0.10.0"
criterion = "0.3.0"

edgeware-testing = { path = "../testing" }

[features]
wasmtime = [
    "sc-executor/wasmtime",
]
wasmi-errno = [
    "sc-executor/wasmi-errno",
]
stress-test = []

[[bench]]
name = "bench"
harness = false
